### PR TITLE
Add xunit, rocketchatnotifier, monitoring plugins, and correct order

### LINKED ISSUE #25: Install various plugins on Jenkins master
I've currently done it manually, please add it to Puppet.

- Xunit
- Monitoring
- Rocket.Chat

### PR DESCRIPTION
**Pull request by antgel**
Closes #25

### CODE REVIEW

**Comment by alvagante** [comment]
Looks ok. Note that we can start to cleanup the hieradata a bit and keep only the files we actually use, this would make it easier to evaluate the parameters used by different nodes

**Review by alvagante — APPROVED** [review]
Not testes if plugins are actually correctly installed, but syntax is ok

**Comment by antgel** [comment]
@alvagante Thanks, I'll merge to `master`, feel free to do the same in future PRs you approve. :)

**Comment by antgel** [comment]
As for cleaning up the hieradata, I personally actually quite enjoy having the boilerplate around as "inspiration". :)

**Pull request merged**
